name: CI/CD Pipeline with Delphi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy
        env:
            PRIVATE_KEY: ${{ secrets.KEY }}
            HOSTNAME: ${{secrets.HOST}}
            USER_NAME: ${{secrets.USERNAME}}
      
        run: |
          echo "$PRIVATE_KEY" > ec2-key.pem && chmod 400 ec2-key.pem
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${USER_NAME}@${HOSTNAME} 'sudo systemctl stopt emissao.service && sudo systemctl start auth.service'
  