name: CI/CD Pipeline with Delphi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest 

    steps:
      - name: SSH # Apenas alterado o keu gerado manualemnte
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo systemctl start emissao.service
            sudo systemctl start auth.service
  