name: CI/CD Pipeline with Delphi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest 

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
      
        # run: |
        #   echo "$PRIVATE_KEY" > ec2-key.pem && chmod 400 ec2-key.pem
        #   ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${USER_NAME}@${HOSTNAME} 'sudo systemctl stopt emissao.service && sudo systemctl start auth.service'
  