name: CI/CD Pipeline with Delphi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest 

    steps:
      - name: SSH 
        uses: appleboy/ssh-action@master #alterada a chave
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo systemctl start emissao.service
            sudo systemctl start auth.service
  