name: CI/CD Pipeline with Delphi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest 

    steps:
      - name: Deploy EC2
        uses: actions/checkout@v2
        env:
            PRIVATE_KEY: ${{ secrets.KEY }}
            HOSTNAME: ${{secrets.HOST}}
            USER_NAME: ${{secrets.USERNAME}}
          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -i private_key ${USER_NAME}@${HOSTNAME} 'sudo systemctl stopt emissao.service && sudo systemctl start auth.service'
  